-- Backfill xp_earned for invoices created before migration 026.
-- Mirrors the toNSU() logic in src/utils/pricing.js: CEIL(gross_amount / divisor).
-- Invoices already written with xp_earned > 0 (post-026) are left untouched.
UPDATE invoices
SET xp_earned = CEIL(
  gross_amount::numeric / CASE currency
    -- North & Central America
    WHEN 'MXN' THEN 17    WHEN 'GTQ' THEN 8     WHEN 'BZD' THEN 2
    WHEN 'HNL' THEN 25    WHEN 'NIO' THEN 40    WHEN 'CRC' THEN 500
    WHEN 'CUP' THEN 25    WHEN 'JMD' THEN 150   WHEN 'TTD' THEN 7
    WHEN 'DOP' THEN 60    WHEN 'HTG' THEN 130
    -- South America
    WHEN 'ARS' THEN 1000  WHEN 'CLP' THEN 1000  WHEN 'UYU' THEN 40
    WHEN 'PYG' THEN 8000  WHEN 'BOB' THEN 7     WHEN 'PEN' THEN 4
    WHEN 'COP' THEN 4000  WHEN 'VES' THEN 40    WHEN 'BRL' THEN 6
    WHEN 'GYD' THEN 200   WHEN 'SRD' THEN 40
    -- Europe
    WHEN 'NOK' THEN 10    WHEN 'SEK' THEN 10    WHEN 'DKK' THEN 7
    WHEN 'ISK' THEN 140   WHEN 'CZK' THEN 25    WHEN 'PLN' THEN 4
    WHEN 'HUF' THEN 400   WHEN 'RON' THEN 5     WHEN 'BGN' THEN 2
    WHEN 'RSD' THEN 110   WHEN 'BAM' THEN 2     WHEN 'MKD' THEN 60
    WHEN 'ALL' THEN 110   WHEN 'MDL' THEN 18    WHEN 'UAH' THEN 40
    WHEN 'BYN' THEN 3     WHEN 'RUB' THEN 90    WHEN 'GEL' THEN 3
    WHEN 'TRY' THEN 40
    -- East Asia
    WHEN 'JPY' THEN 100   WHEN 'CNY' THEN 7     WHEN 'KRW' THEN 1000
    WHEN 'KPW' THEN 900   WHEN 'TWD' THEN 30    WHEN 'HKD' THEN 8
    WHEN 'MOP' THEN 8     WHEN 'MNT' THEN 3500
    -- South & Southeast Asia
    WHEN 'INR' THEN 85    WHEN 'PKR' THEN 280   WHEN 'BDT' THEN 110
    WHEN 'LKR' THEN 300   WHEN 'NPR' THEN 130   WHEN 'BTN' THEN 85
    WHEN 'MVR' THEN 15    WHEN 'MYR' THEN 5     WHEN 'IDR' THEN 16000
    WHEN 'PHP' THEN 60    WHEN 'THB' THEN 35    WHEN 'VND' THEN 25000
    WHEN 'KHR' THEN 4000  WHEN 'LAK' THEN 22000 WHEN 'MMK' THEN 2000
    -- Central Asia
    WHEN 'KZT' THEN 500   WHEN 'UZS' THEN 13000 WHEN 'KGS' THEN 90
    WHEN 'TJS' THEN 10    WHEN 'TMT' THEN 4     WHEN 'AZN' THEN 2
    WHEN 'AMD' THEN 400
    -- Middle East
    WHEN 'AED' THEN 4     WHEN 'SAR' THEN 4     WHEN 'QAR' THEN 4
    WHEN 'ILS' THEN 4     WHEN 'LBP' THEN 90000 WHEN 'SYP' THEN 13000
    WHEN 'IQD' THEN 1300  WHEN 'IRR' THEN 42000 WHEN 'YER' THEN 250
    -- Oceania
    WHEN 'AUD' THEN 2     WHEN 'NZD' THEN 2     WHEN 'FJD' THEN 2
    WHEN 'PGK' THEN 4
    -- Africa
    WHEN 'ZAR' THEN 20    WHEN 'NGN' THEN 1600  WHEN 'KES' THEN 130
    WHEN 'GHS' THEN 15    WHEN 'EGP' THEN 50    WHEN 'MAD' THEN 10
    WHEN 'DZD' THEN 130   WHEN 'TND' THEN 3     WHEN 'LYD' THEN 5
    WHEN 'ETB' THEN 60    WHEN 'UGX' THEN 4000  WHEN 'TZS' THEN 2500
    WHEN 'RWF' THEN 1300  WHEN 'BIF' THEN 3000  WHEN 'XOF' THEN 600
    WHEN 'XAF' THEN 600   WHEN 'AOA' THEN 900   WHEN 'ZMW' THEN 25
    WHEN 'MWK' THEN 2000  WHEN 'MZN' THEN 65    WHEN 'NAD' THEN 20
    WHEN 'BWP' THEN 15    WHEN 'SDG' THEN 600   WHEN 'SSP' THEN 2000
    WHEN 'ERN' THEN 15    WHEN 'SZL' THEN 20    WHEN 'LSL' THEN 20
    WHEN 'LRD' THEN 200   WHEN 'SOS' THEN 600   WHEN 'GMD' THEN 70
    WHEN 'GNF' THEN 9000  WHEN 'MRU' THEN 40    WHEN 'MUR' THEN 45
    WHEN 'CVE' THEN 110   WHEN 'SLE' THEN 23    WHEN 'DJF' THEN 180
    WHEN 'KMF' THEN 450   WHEN 'CDF' THEN 3000  WHEN 'MGA' THEN 4500
    WHEN 'AFN' THEN 70
    ELSE 1
  END
)::integer
WHERE xp_earned IS NULL AND gross_amount > 0;
